// Original Figma assets, served locally. Identical exports share a single file.
export const assets = {
  blogArticle: {
    imgImage64: "/figma/blogArticle-imgImage64.png",
    imgImageTheTeamAroundTheLongDeskLaptopsOpen:
      "/figma/blogArticle-imgImageTheTeamAroundTheLongDeskLaptopsOpen.png",
    imgImageAHandOfPokerPlayingOutOnTheBoardroomTable:
      "/figma/blogArticle-imgImageAHandOfPokerPlayingOutOnTheBoardroomTable.png",
    imgImageARooftopGroupPhotoWithTheCityLitUpBehind:
      "/figma/blogArticle-imgImageARooftopGroupPhotoWithTheCityLitUpBehind.png",
    imgImageASelfieCrowdedInBesideTheCoffeeMachine:
      "/figma/blogArticle-imgImageASelfieCrowdedInBesideTheCoffeeMachine.png",
    imgImagePizzaOnTheConferenceTableATeammateDialledInOnTheScreen:
      "/figma/blogArticle-imgImagePizzaOnTheConferenceTableATeammateDialledInOnTheScreen.png",
    imgImageDessertPresentedToTheCameraInTheOfficePantry:
      "/figma/blogArticle-imgImageDessertPresentedToTheCameraInTheOfficePantry.png",
    imgImageAPujaOnTheOfficeFloorEveryoneSittingTogether:
      "/figma/blogArticle-imgImageAPujaOnTheOfficeFloorEveryoneSittingTogether.png",
    imgImage67: "/figma/blogArticle-imgImage67.png",
    imgEllipse4058: "/figma/blogArticle-imgEllipse4058.svg",
    imgEllipse4059: "/figma/blogArticle-imgEllipse4059.svg",
    imgEllipse4060: "/figma/blogArticle-imgEllipse4060.svg",
    imgEllipse4061: "/figma/blogArticle-imgEllipse4061.svg",
    imgEllipse4074: "/figma/blogArticle-imgEllipse4074.svg",
    imgImage68: "/figma/blogArticle-imgImage68.svg",
    imgEllipse4072: "/figma/blogArticle-imgEllipse4072.svg",
    imgEllipse4071: "/figma/blogArticle-imgEllipse4071.svg",
  },
  home: {
    imgImage39: "/figma/home-imgImage39.png",
    imgObject: "/figma/home-imgObject.png",
    imgImage50: "/figma/home-imgImage50.png",
    imgImage51: "/figma/home-imgImage51.png",
    imgEllipse4061: "/figma/home-imgEllipse4061.png",
    imgEllipse4062: "/figma/home-imgEllipse4062.png",
    imgVideo: "/figma/home-imgVideo.png",
    imgVideo1: "/figma/home-imgVideo1.png",
    imgVideo2: "/figma/home-imgVideo2.png",
    imgEllipse4069: "/figma/home-imgEllipse4069.png",
    imgEllipse4068: "/figma/home-imgEllipse4068.png",
    imgEllipse4070: "/figma/home-imgEllipse4070.png",
    imgImage48: "/figma/home-imgImage48.png",
    imgImage57: "/figma/home-imgImage57.png",
    imgImage58: "/figma/home-imgImage58.png",
    imgImage56: "/figma/home-imgImage56.png",
    imgImageCnvrted: "/figma/home-imgImageCnvrted.png",
    imgImage53: "/figma/home-imgImage53.png",
    imgEllipse4058: "/figma/home-imgEllipse4058.svg",
    imgEllipse4059: "/figma/home-imgEllipse4059.svg",
    imgImageDatatim: "/figma/home-imgImageDatatim.svg",
    imgImageSpectroCloud: "/figma/home-imgImageSpectroCloud.svg",
    imgImageFlip: "/figma/home-imgImageFlip.svg",
    imgImageUnum: "/figma/home-imgImageUnum.svg",
    imgImagePrimer: "/figma/home-imgImagePrimer.svg",
    imgBookOpenText: "/figma/home-imgBookOpenText.svg",
    imgInfo: "/figma/home-imgInfo.svg",
    imgGroup1437254394: "/figma/home-imgGroup1437254394.svg",
    imgArrow1: "/figma/home-imgArrow1.svg",
    imgVector: "/figma/home-imgVector.svg",
    imgVector1: "/figma/home-imgVector1.svg",
    imgVector2: "/figma/home-imgVector2.svg",
    imgVector3: "/figma/home-imgVector3.svg",
    imgVector4: "/figma/home-imgVector4.svg",
    imgVector5: "/figma/home-imgVector5.svg",
    imgVector6: "/figma/home-imgVector6.svg",
    imgVector7: "/figma/home-imgVector7.svg",
    imgVector8: "/figma/home-imgVector8.svg",
    imgVector9: "/figma/home-imgVector9.svg",
    imgVector10: "/figma/home-imgVector10.svg",
    imgVector11: "/figma/home-imgVector11.svg",
    imgVector12: "/figma/home-imgVector12.svg",
    imgVector13: "/figma/home-imgVector13.svg",
    imgVector14: "/figma/home-imgVector14.svg",
    imgVector15: "/figma/home-imgVector15.svg",
    imgVector16: "/figma/home-imgVector16.svg",
    imgVector17: "/figma/home-imgVector17.svg",
    imgCheckCircle: "/figma/home-imgCheckCircle.svg",
    imgEllipse4060: "/figma/home-imgEllipse4060.svg",
    imgPaperPlaneTilt: "/figma/home-imgPaperPlaneTilt.svg",
    imgVector202: "/figma/home-imgVector202.svg",
    imgVector203: "/figma/home-imgVector203.svg",
    imgInfinity: "/figma/home-imgInfinity.svg",
    imgIcon: "/figma/home-imgIcon.svg",
    imgContainer: "/figma/home-imgContainer.svg",
    imgRowsPlusBottom: "/figma/home-imgRowsPlusBottom.svg",
    imgHubspotIcon1: "/figma/home-imgHubspotIcon1.svg",
    imgFrame1686561841: "/figma/home-imgFrame1686561841.svg",
    imgSlackIcon20191: "/figma/home-imgSlackIcon20191.svg",
    imgCdnlogoComZapierLogo1: "/figma/home-imgCdnlogoComZapierLogo1.svg",
    imgCopilotIcon1: "/figma/home-imgCopilotIcon1.svg",
    imgGroup: "/figma/home-imgGroup.svg",
    imgIcon1: "/figma/home-imgIcon1.svg",
    imgCnvrted: "/figma/home-imgCnvrted.svg",
    imgIcon2: "/figma/home-imgIcon2.svg",
    imgIcon3: "/figma/home-imgIcon3.svg",
    imgIcon4: "/figma/home-imgIcon4.svg",
    imgIcon5: "/figma/home-imgIcon5.svg",
    imgVector18: "/figma/home-imgVector18.svg",
    imgCopilotIcon2: "/figma/home-imgCopilotIcon2.svg",
  },
  blogListing: {
    imgImage61: "/figma/blogListing-imgImage61.png",
    imgEllipse4058: "/figma/blogListing-imgEllipse4058.svg",
    imgEllipse4059: "/figma/blogListing-imgEllipse4059.svg",
    imgIcon5: "/figma/blogListing-imgIcon5.svg",
    imgIcon6: "/figma/blogListing-imgIcon6.svg",
  },
  careers: {
    imgImage60: "/figma/careers-imgImage60.png",
    imgObject: "/figma/home-imgObject.png",
    imgEllipse4058: "/figma/careers-imgEllipse4058.svg",
    imgEllipse4059: "/figma/careers-imgEllipse4059.svg",
    imgMagnifyingGlass: "/figma/careers-imgMagnifyingGlass.svg",
    imgCaretDown: "/figma/careers-imgCaretDown.svg",
    imgArrowRight: "/figma/careers-imgArrowRight.svg",
  },
} as const;
